### ISSUE TITLE
Fix: Update Sudoku to use multiple sprite groups instead of one

### ISSUE THREAD

**Issue by alecpramanik** [BevapnadeBerit/Proj_INDA#18]
See https://github.com/BevapnadeBerit/Proj_INDA/pull/14#pullrequestreview-1409825633.

All calls to `set_value` in `Sudoku` need to be passing a sprite groups dict after the changes above. A field that stores this sprite group in the `Grid` object would be useful for retrieving this dict.

**Comment by BevapnadeBerit** [comment]
Remember to close this issue and relabel cause this is rather an enhancement than a bug.

**Comment by alecpramanik** [comment]
Irrelevant as of PR https://github.com/BevapnadeBerit/Proj_INDA/pull/19
